country_codes_map = {'us': 'United States',
 'ae': 'United Arab Emirates',
 'ae-ar': 'United Arab Emirates',
 'am': 'Armenia',
 'at': 'Austria',
 'au': 'Australia',
 'befr': 'Belgium',
 'benl': 'Belgium',
 'bg': 'Bulgaria',
 'bh': 'Bahrain',
 'br': 'Brazil',
 'bw': 'Botswana',
 'ca': 'Canada',
 'cafr': 'Canada',
 'cf': 'Republic of Central Africa',
 'chde': 'Switzerland',
 'chfr': 'Switzerland',
 'ci': "Ivory Coast",
 'cl': 'Chile',
 'cm': 'Cameroon',
 'cn': 'China',
 'co': 'Colombia',
 'cz': 'Czeckslovakia',
 'de': 'Germany',
 'dk': 'Denmark',
 'ee': 'Estonia',
 'eg': 'Egypt',
 'es': 'Spain',
 'fi': 'Finland',
 'fr': 'France',
 'gn': 'Guinea',
 'gq': 'Guinea Equator',
 'gr': 'Greece',
 'gw': 'Guinea-Bissau',
 'hk': 'Hong Kong',
 'hken': 'Hong Kong',
 'hr': 'Croatia',
 'hu': 'Hungary',
 'id': 'Indonesia',
 'ie': 'Ireland',
 'il': 'Israel',
 'in': 'India',
 'it': 'Italia',
 'jo': 'Jordan',
 'jp': 'Japan',
 'ke': 'Kenya',
 'kr': 'South Korea',
 'kw': 'Kuwait',
 'la': 'Latin America and Caribbean',
 'lae': 'Latin America and Caribbean',
 'li': 'Liechtenstein',
 'lt': 'Lithuania',
 'lu': 'Luxembourg',
 'lv': 'Latvia',
 'ma': 'Morocco',
 'md': 'Moldova',
 'me': 'Montenegro',
 'mg': 'Madagascar',
 'mk': 'Macedonia',
 'ml': 'Mali',
 'mo': 'Mongolia',
 'mt': 'Malta',
 'mu': 'Maurice',
 'mx': 'Mexico',
 'my': 'Malaysia',
 'mz': 'Mozambique',
 'ne': 'Niger',
 'ng': 'Nigeria',
 'nl': 'Netherland',
 'no': 'Norway',
 'nz': 'New Zealand',
 'om': 'Oman',
 'ph': 'Philippines',
 'pl': 'Poland',
 'pt': 'Portugal',
 'qa': 'Qatar',
 'ro': 'Romania',
 'ru': 'Russia',
 'sa': 'Saudi Arabia',
 'sa-ar': 'Saudi Arabia',
 'se': 'Sweden',
 'sg': 'Singapore',
 'si': 'Slovenia',
 'sk': 'Slovakia',
 'sn': 'Senegal',
 'th': 'Thailand',
 'tn': 'Tunisia',
 'tr': 'Turkey',
 'tw': 'Taiwan',
 'ug': 'Uganda',
 'uk': 'United Kingdom',
 'vn': 'Vietnam',
 'za': 'South Africa'
}
